/**
 * Project Tracker
 * Backend for a simple CRUD example application to track different projects
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * comment to a project
 */
export interface Comment {
    /**
     * internal id of comment, gets created by system
     */
    id?: number;

    /**
     * id of project this comment is about
     */
    project?: number;

    /**
     * actual comment
     */
    comment?: string;

    /**
     * timestamp of this comment
     */
    timestamp?: Date;

    /**
     * id of the user this comment came from
     */
    user?: number;

}
