/**
 * Project Tracker
 * Backend for a simple CRUD example application to track different projects
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * general message from backend to the frontend or client
 */
export interface Message {
    /**
     * A response message from the app.
     */
    message?: string;

}
