/**
 * Project Tracker
 * Backend for a simple CRUD example application to track different projects
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * core object, the projects to track
 */
export interface Project {
    /**
     * internal id of project, gets created by system
     */
    id?: number;

    /**
     * id of parent project so projects can be organized
     */
    parent?: number;

    name?: string;

    /**
     * id of customer this project is done for
     */
    customer?: number;

    /**
     * start date of project
     */
    startdate?: Date;

    /**
     * end date of project
     */
    enddate?: Date;

    /**
     * type of this project
     */
    type?: Project.TypeEnum;

    /**
     * kind of project
     */
    kind?: Project.KindEnum;

}
export namespace Project {
    export enum TypeEnum {
        Kundenprojekt = <any> 'Kundenprojekt',
        InternesProjekt = <any> 'internes Projekt',
        Untergeordnet = <any> 'untergeordnet',
        Offen = <any> 'offen'
    }
    export enum KindEnum {
        Beratung = <any> 'Beratung',
        SBF = <any> 'SBF',
        RARRD = <any> 'RA / RRD',
        SBFRARRD = <any> 'SBF / RA / RRD',
        Sonstiges = <any> 'Sonstiges'
    }
}
