/**
 * Project Tracker
 * Backend for a simple CRUD example application to track different projects
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * status of project. There can be different owners of statuses - customer, internal etc.
 */
export interface Status {
    /**
     * internal id of status, gets created by system
     */
    id?: number;

    /**
     * owner of status to differentiate between status by customer and internal status
     */
    owner?: string;

    /**
     * status code, normally a number between 01 and 99, should be formatted as 00
     */
    code?: number;

    /**
     * name of status, for example \"planned\", \"staffed\", \"finished\"
     */
    status?: string;

}
